# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: knigipodarki
  pool: 5
  username: knigipodarki
  password: wrle2la5m
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: knigipodarki
  pool: 5
  username: knigipodarki
  password: wrle2la5m
  host: localhost